### ISSUE TITLE
AttributeError: 'FieldInfo' object has no attribute 'in_'

### ISSUE THREAD

**Issue by eniora** [harisreedhar/Swap-Mukham#40]
Everything loads up fine but at the end the program closes and I get **AttributeError: 'FieldInfo' object has no attribute 'in_'**
Any idea how to fix this? thanks.

Here's the full log:

Traceback (most recent call last):
  File "C:\Swap-Mukham\app.py", line 514, in <module>
    with gr.Blocks(css=css) as interface:
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1478, in __exit__
    self.app = routes.App.create_app(self)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 220, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 706, in decorator
    self.add_api_route(
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 645, in add_api_route
    route = route_class(
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 491, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 268, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 111, in get_param_sub_dependant
    return get_sub_dependant(
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 147, in get_sub_dependant
    sub_dependant = get_dependant(
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 289, in get_dependant
    add_param_to_fields(field=param_field, dependant=dependant)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 462, in add_param_to_fields
    if field_info.in_ == params.ParamTypes.path:
AttributeError: 'FieldInfo' object has no attribute 'in_'

**Comment by harisreedhar** [comment]
Haven't seen this error before. Are you sure using same code as in the repo?

**Comment by harisreedhar** [comment]
> Yah I also tried to git clone it again. Weird thing is that it was working fine but I screwed up my python installation and had to remove everything and reinstall python (even deleted the appdata python folder before reinstalling). After reinstallation everything working good including A1111, normal roop, comfyui etc. except for Swap-Mukham, it throws this error. Tried installing the requirements multiple times but to no avail.
> ~~I will try again tomorrow, not near the PC to troubleshoot it, but~~ if you have any idea what could be wrong please tell me so I can try tomorrow. Thanks :)
> 
> Edit: I tried on another PC just now and I am getting the same error, that's really weird. I am here if you have any idea and can try :D
> 
> can you please check https://github.com/tiangolo/fastapi/issues/1007 and see if anything can be done? they mentioned this error and how you can solve it. I am no expert and know nothing about programming :P
> 
> Edit 2: just tried from a conda environment and the exact same error. I think at this point I tried everything possible.

Uninstall fastapi & gradio using pip and try different version of gradio that works for you

**Comment by Ratfiend** [comment]
I've just had the same error.

So I tried:
> pip uninstall fastapi (Successfully uninstalled fastapi-0.100.0)
and
> pip install fastapi==0.99.1

Now it works.

**Comment by eniora** [comment]
Uninstalling only fastapi and installing 0.99.1 solved it for me finally. Thank you both!
