### ISSUE TITLE
Probably a simple fix...

### ISSUE THREAD

**Issue by milksteak1111** [harisreedhar/Swap-Mukham#64]
Checking for NSFW contents: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.30it/s]
0 face detected. Using best detection face.
Traceback (most recent call last):
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\gradio\routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\gradio\utils.py", line 508, in async_iteration
    return await iterator.__anext__()
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\gradio\utils.py", line 501, in __anext__
    return await anyio.to_thread.run_sync(
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\gradio\utils.py", line 484, in run_sync_iterator_async
    return next(iterator)
  File "A:\CONDA\envs\Swap-mukham\lib\site-packages\gradio\utils.py", line 853, in gen_wrapper
    yield from f(*args, **kwargs)
  File "A:\Swap-Mukham\app.py", line 356, in process
    for info_update in swap_process([output_file]):
  File "A:\Swap-Mukham\app.py", line 247, in swap_process
    analysed_targets, analysed_sources, whole_frame_list, num_faces_per_frame = get_analysed_data(
  File "A:\Swap-Mukham\face_analyser.py", line 85, in get_analysed_data
    analysed_source = analyse_face(source_image, face_analyser, return_single_face=True, detect_condition=detect_condition, scale=scale)
  File "A:\Swap-Mukham\face_analyser.py", line 72, in analyse_face
    return get_single_face(faces, method=detect_condition)
  File "A:\Swap-Mukham\face_analyser.py", line 41, in get_single_face
    return sorted(faces, key=lambda face: face["det_score"])[-1]
IndexError: list index out of range

I keep getting this error and was just wondering if it was something obvious to you, thanks

**Comment by G-force78** [comment]
It cant detect a face, maybe the image is blurry, obscured by facial hair, at a weird angle or something like that.

**Comment by milksteak1111** [comment]
Yep it was just a face that was too large, I had upscaled it too much to try and make it more easy to copy and it couldn't detect it, thanks!

**Comment by harisreedhar** [comment]
> Yep it was just a face that was too large, I had upscaled it too much to try and make it more easy to copy and it couldn't detect it, thanks!

Using lower detection threshold like 0.3 or 0.4 will detect closeup faces. (This error is fixed in upcomming version)

**Comment by jndietz** [comment]
Had the same issue - just lowered the threshold and it was resolved.
