### ISSUE TITLE
Full-on Colab Implementation

### ISSUE THREAD

**Issue by prateeknc** [harisreedhar/Swap-Mukham#69]
Please create a notebook to implement face swapping without using Gradio. 

Gradio is getting banned across free GPU providers.

**Comment by G-force78** [comment]
and a sagemaker notebook as I cant seem to get it to launch a gradio link

Traceback (most recent call last):
  File "/home/studio-lab-user/Swap-Mukham/app.py", line 632, in <module>
    mask_include = gr.Dropdown(
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/gradio/components.py", line 1232, in __init__
    Radio.__init__(
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/gradio/components.py", line 1092, in __init__
    self.test_input = self.choices[0] if len(self.choices) else None
TypeError: 'dict_keys' object is not subscriptable

**Comment by harisreedhar** [comment]
@prateeknc @G-force78 I'll add a CLI interface but it takes time. I have other works to do.
